const INCIDENT_CATEGORIES = {
  ACCIDENT: 'ACCIDENT',
  FIRE: 'FIRE',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  ROAD_HAZARD: 'ROAD_HAZARD',
  FLOOD_WATERLOGGING: 'FLOOD_WATERLOGGING',
  MEDICAL_EMERGENCY: 'MEDICAL_EMERGENCY',
  INFRASTRUCTURE_ISSUE: 'INFRASTRUCTURE_ISSUE',
  OTHER: 'OTHER',
};

const VALID_CATEGORIES = Object.values(INCIDENT_CATEGORIES);

module.exports = {
  INCIDENT_CATEGORIES,
  VALID_CATEGORIES,
};
