const INCIDENT_STATUS = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  RESOLVED: 'RESOLVED',
  CANCELLED: 'CANCELLED',
};

const VALID_STATUSES = Object.values(INCIDENT_STATUS);

module.exports = {
  INCIDENT_STATUS,
  VALID_STATUSES,
};
