/**
 * Notification Types Constants for Module 7: Real-Time Communication & Notifications
 */

const NOTIFICATION_TYPES = {
  INCIDENT_NEARBY: 'INCIDENT_NEARBY',
  ALERT_CREATED: 'ALERT_CREATED',
  ALERT_UPDATED: 'ALERT_UPDATED',
  ALERT_RESOLVED: 'ALERT_RESOLVED',
  SOS_NOTIFICATION: 'SOS_NOTIFICATION',
  COMMUNITY_VERIFICATION: 'COMMUNITY_VERIFICATION',
  SYSTEM: 'SYSTEM',
};

const VALID_NOTIFICATION_TYPES = Object.values(NOTIFICATION_TYPES);

module.exports = {
  NOTIFICATION_TYPES,
  VALID_NOTIFICATION_TYPES,
};
