/**
 * Verification Types & Community Status Constants for Module 5
 */

const VERIFICATION_TYPES = {
  CONFIRM: 'CONFIRM',
  DISPUTE: 'DISPUTE',
};

const COMMUNITY_STATUS = {
  UNVERIFIED: 'UNVERIFIED',
  COMMUNITY_CONFIRMED: 'COMMUNITY_CONFIRMED',
  COMMUNITY_DISPUTED: 'COMMUNITY_DISPUTED',
};

const VALID_VERIFICATION_TYPES = Object.values(VERIFICATION_TYPES);
const VALID_COMMUNITY_STATUSES = Object.values(COMMUNITY_STATUS);

module.exports = {
  VERIFICATION_TYPES,
  COMMUNITY_STATUS,
  VALID_VERIFICATION_TYPES,
  VALID_COMMUNITY_STATUSES,
};
